# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sys_info.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_System_info(object):
    def setupUi(self, System_info):
        System_info.setObjectName("System_info")
        System_info.resize(593, 442)
        self.verticalLayout = QtWidgets.QVBoxLayout(System_info)
        self.verticalLayout.setObjectName("verticalLayout")
        self.os = QtWidgets.QLabel(System_info)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.os.setFont(font)
        self.os.setStyleSheet("")
        self.os.setTextFormat(QtCore.Qt.AutoText)
        self.os.setObjectName("os")
        self.verticalLayout.addWidget(self.os)
        self.cpu = QtWidgets.QLabel(System_info)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.cpu.setFont(font)
        self.cpu.setStyleSheet("")
        self.cpu.setTextFormat(QtCore.Qt.AutoText)
        self.cpu.setObjectName("cpu")
        self.verticalLayout.addWidget(self.cpu)
        self.ram = QtWidgets.QLabel(System_info)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ram.setFont(font)
        self.ram.setStyleSheet("")
        self.ram.setTextFormat(QtCore.Qt.AutoText)
        self.ram.setObjectName("ram")
        self.verticalLayout.addWidget(self.ram)
        self.gc = QtWidgets.QLabel(System_info)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gc.setFont(font)
        self.gc.setStyleSheet("")
        self.gc.setTextFormat(QtCore.Qt.AutoText)
        self.gc.setObjectName("gc")
        self.verticalLayout.addWidget(self.gc)
        self.go_home1 = QtWidgets.QPushButton(System_info)
        self.go_home1.setObjectName("go_home1")
        self.verticalLayout.addWidget(self.go_home1)

        self.retranslateUi(System_info)
        QtCore.QMetaObject.connectSlotsByName(System_info)

    def retranslateUi(self, System_info):
        _translate = QtCore.QCoreApplication.translate
        System_info.setWindowTitle(_translate("System_info", "Dialog"))
        self.os.setText(_translate("System_info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Версия винды: </span></p></body></html>"))
        self.cpu.setText(_translate("System_info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">ЦП: </span></p></body></html>"))
        self.ram.setText(_translate("System_info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Оператива: </span></p></body></html>"))
        self.gc.setText(_translate("System_info", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Видеокарта: </span></p></body></html>"))
        self.go_home1.setText(_translate("System_info", "Вернуться домой"))

